name: Build and Deploy
on:
  push:
    branches:
    - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - name: Cache Bun
        uses: actions/cache@v4
        env:
          cache-name: cache-bun-v1
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('bun.lockb') }}
      
      - name: Deps
        run: bun i --frozen-lockfile
      
      - name: Build
        run: bun run build
      
      - name: Store build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error
          retention-days: 1
          overwrite: true

  pdf:
    name: PDF
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Get PNPM store directory
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache Bun
        uses: actions/cache@v4
        env:
          cache-name: cache-bun-v1
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('bun.lockb') }}
      - name: Cache PNPM
        uses: actions/cache@v4
        env:
          cache-name: cache-pnpm-v1
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('playwright/pnpm-lock.yaml') }}
      - name: Cache Playwright
        uses: actions/cache@v4
        env:
          cache-name: cache-playwright-v1
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('playwright/pnpm-lock.yaml') }}

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
        
      - name: Deps
        run: bun i --frozen-lockfile && cd playwright && pnpm deps
      
      - name: PDF
        run: |
          bun run serve &
          cd playwright && pnpm start
      
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error
          retention-days: 1
          overwrite: true

  deploy:
    name: Deploy
    needs: [build, pdf]
    if: needs.build.result == 'success'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy pages
        uses: actions/deploy-pages@v4
        id: deployment
